volumes:
  pgdata:

services:
  db:
    image: docker.io/library/postgres:alpine
    container_name: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    shm_size: 128mb
    restart: unless-stopped

  server:
    image: localhost/t3-app-go
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: unless-stopped
