-- +goose Up

CREATE TABLE departments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL CHECK (name != ''),
    parent_id INTEGER REFERENCES departments(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE departments
ADD CONSTRAINT parent_not_self 
CHECK (parent_id != id);

-- Индекс для ускорения запросов по parent_id (часто нужен для построения дерева)
CREATE INDEX idx_departments_parent_id ON departments(parent_id);
-- Индексы обеспечивающие уникальность имен предприятий:
-- На верхнем уровне
CREATE UNIQUE INDEX idx_unique_dept_name_root ON departments (name) WHERE parent_id IS NULL;
-- У дочерних предприятий в рамках одного родительского
CREATE UNIQUE INDEX idx_unique_dept_name_per_parent ON departments (parent_id, name) WHERE parent_id IS NOT NULL;

CREATE TABLE employees (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INTEGER NOT NULL REFERENCES departments(id),
    full_name varchar(200) NOT NULL CHECK (full_name != ''),
    position varchar(200) NOT NULL CHECK (position != ''),
    hired_at DATE NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- +goose Down
 
DROP TABLE employees;
DROP TABLE departments;
